---
    - name: Configure
      shell:
        cmd: |
          cat > /tmp/a.txt << EOF
          This is a
          EOF
          echo "this is new line" >> /tmp/a.txt
    - name: Configure2
      shell: modprobe overlay
    - name: Configure3
      shell: modprobe br_netfilter
    - name: Setup required sysctl params, these persist across reboots.
      shell:
        cmd: |
          cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          EOF
    - name: Configure3
      shell: sysctl --system