---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
data:
  config: |
    server {
        listen       80;
        location / {
          return 200 "${MY_NODE_NAME}";
          add_header Content-Type text/plain;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001
      name: http
  selector:
    name: nginx
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  namespace: default
  labels:
    k8s-app: nginx-app
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-vol
            mountPath: /etc/nginx/templates/
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      volumes:
        - name: config-vol
          configMap:
            name: proxy-config
            items:
              - key: config
                path: default.conf.template