---
    - name: Initialize the control-plane node
      shell: kubeadm init --pod-network-cidr=10.0.0.0/16
    - name: Create a directory if it does not exist
      file:
        path: $HOME/.kube
        state: directory
    - name: Copy file with owner and permissions
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: true
    - name: Set kubeconfig file permission
      file:
        path: $HOME/.kube/config
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
    - name: Test
      shell: echo "{{ ansible_effective_user_id }}" >> test1.txt
      args:
        chdir: $HOME
    - name: Test2
      shell: echo "{{ ansible_effective_group_id }}" >> test2.txt
      args:
        chdir: $HOME
    - name: Download the Calico networking manifest
      get_url:
        url: https://projectcalico.docs.tigera.io/manifests/calico.yaml
        dest: $HOME/calico.yaml
    - name: Install pod network
      shell: kubectl apply -f $HOME/calico.yaml
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
      args:
        chdir: $HOME
    - name: test3
      shell: echo "{{ join_command_raw }}" >> test3.txt
      args:
        chdir: $HOME
    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"