---
- hosts: masters:workers
  become: true
  roles:
    - ping
    - swap
    - reboot
    - containerd
    - docker
    - kubernetes
- hosts: masters
  become: true
  roles:
    - kubernetes_master
- hosts: workers
  become: true
  roles:
    - kubernetes_worker